"""add is_deleted to jobs

Revision ID: bf470aa4283f
Revises: 0c0922bab77b
Create Date: 2026-07-24 22:28:18.211166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf470aa4283f'
down_revision: Union[str, Sequence[str], None] = '0c0922bab77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_deleted')
    # ### end Alembic commands ###
